### ISSUE TITLE
ERROR:root:Docker version must be <=1.9.1

### ISSUE THREAD

**Issue by asmod3us** [coursera/courseraprogramming#38]
I'm on a Mac with `Docker version 1.9.1, build a34a1d5` but I'm getting the error stated in the title. The semver check in sanity.py looks like it should be successful with this version, so not really sure what's going on. Can you help me debug?

**Comment by saeta** [comment]
Hi @asmod3us It appears as if the latest docker-machine code always downloads the latest version of the server component of Docker (found in the vagrant VM). As a result, on a Mac, it's very difficult to get a properly compliant version of the Docker client & server. (You can see the different versions of the Docker client vs the docker server by running `docker version`.)

Good news: `courseraprogramming` works just fine with any (currently released) version of docker > 1.5 including Docker 1.10.

Bad news: The production environment only works with Docker > 1.5.0 and <= 1.9.1. This is due to some added security measures that broke in Docker 1.10. (`courseraprogramming upload` will appear to succeed, but your uploaded image will not properly register.)

Good news: I'm currently working on fixing that, and we hope to get it resolved within the next 2 weeks. So as long as you don't need to launch your course within the next ~3 weeks (1 extra week for testing in our production environment), then you can safely ignore this warning, and carry on.

As an alternative, I've found that it's fairly straight forward to provision a Linux Cloud VM with older versions of Docker. I launch a stock Ubuntu 14.04 AMI and then follow the [Docker Ubuntu Install Guide](https://docs.docker.com/engine/installation/linux/ubuntulinux/), modifying the line `sudo apt-get install docker-engine` to instead be: `sudo apt-get install docker-engine=1.9.1-0~trusty`.

**Comment by asmod3us** [comment]
hi @saeta, indeed, `docker version` shows that client/server API versions have diverged. Thanks for the hint - I'll try again in a VM.

**Comment by asmod3us** [comment]
Edit: moving this into new issue #39 as it's a different but related error.
