### ISSUE TITLE
Upload exiting with "Killed" and no further feedback.

### ISSUE THREAD

**Issue by asmod3us** [coursera/courseraprogramming#43]
When attempting to upload with `courseraprogramming upload org/img:tag courseId course item part` the cli exits after the following output:

`Saving image org/img:latest to /tmp/org_img:tag.tar...Killed`.

The export with `docker save` seems to have completed, as a new tarball has been created in the working directory. How do I troubleshoot now?

**Comment by saeta** [comment]
@asmod3us thanks for reaching out. It looks like `courseraprogramming` might have been killed due to memory pressure. You can confirm this by checking the syslog / `dmesg`. 

After confirming that the kernel is killing `courseraprogramming` due to memory pressure, the easiest fix would be to free up some memory and re-export. One quick way to determine the amount of required memory would be to look up the size of the image you are trying to export (found in the output of the command `docker images`).

If it is memoy pressure, but it is not possible to either shrink image size or free up enough additional memory (i.e. turning on swap / etc.), it'd be helpful to determine where in the process `courseraprogramming` got killed. To do so, could you reply back with (1) the size of the image, (2) the size of the tar file on disk, (3) all of the relevant lines of the syslog, and (4) the amount of memory available & used on the machine you're running this command? That will help me determine which part of the program to work on optimizing.

Thanks!

**Comment by asmod3us** [comment]
Thanks, you were on the right track with memory pressure. I've upped memory in the vm to four times the images size and the upload is progressing now.
