### ISSUE TITLE
OAuth2 Protocol Exception: Unexpected status code from token endpoint

### ISSUE THREAD

**Issue by anilmuppalla** [coursera/courseraprogramming#67]
courseraoauth2client config authorize --app manage_research_exports
ERROR:root:Encountered unexpected status code: 400 <Response [400]> {"msg":"Invalid Code"}
ERROR:root:Encountered an exception during refresh token flow.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 428, in _exchange_refresh_tokens
    tokens = self._request_tokens_from_token_endpoint(refresh_form)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 325, in _request_tokens_from_token_endpoint
    raise OAuth2Exception('Unexpected status code from token endpoint')
OAuth2Exception: OAuth2 Protocol Exception: Unexpected status code from token endpoint
INFO:root:Attempting to retrieve new tokens from the endpoint. You will be prompted to authorize yourapp in your web browser.
INFO:root:About to request new OAuth2 tokens from Coursera.
Please visit the following URL to authorize this app:
    https://accounts.coursera.org/oauth2/v1/auth?access_type=offline&state=714d92cde26742f894ede12563d79d78&redirect_uri=http%3A%2F%2Flocalhost%3A9876%2Fcallback&response_type=code&client_id=sDHC8Nfp-b1XMbzZx8Wa4w&scope=view_profile

127.0.0.1 - - [12/Oct/2016 19:36:43] "GET /callback?state=714d92cde26742f894ede12563d79d78&code=LyvuEQ_jITf3qtR8yn5qI3bv7Lf1uY3hz2qv5FUyJ6g HTTP/1.1" 200 -
ERROR:root:Encountered unexpected status code: 400 <Response [400]> {"msg":"Invalid Code"}
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/main.py", line 64, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/commands/config.py", line 37, in authorize
    oauth2_instance.build_authorizer()
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 452, in build_authorizer
    new_tokens = self._authorize_new_tokens()
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 415, in _authorize_new_tokens
    return self._request_tokens_from_token_endpoint(form_data)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 325, in _request_tokens_from_token_endpoint
    raise OAuth2Exception('Unexpected status code from token endpoint')
OAuth2Exception: OAuth2 Protocol Exception: Unexpected status code from token endpoint

**Comment by anilmuppalla** [comment]
any help with this? are there instructions to redo the authorization?

**Comment by zhaojunz** [comment]
hey @anilmuppalla,

thanks for using the research export! I tried to reproduce the issue, but I failed to reproduce this locally in my box.

Here are a few suggestions:

1) make sure that you are logged in into coursera.org first.
2) make sure that you are using the latest version of courseraoauth2client client 
`pip install courseraoauth2client --upgrade` can help you to upgrade to the latest version
3) run the same comment with the verbose mode
`courseraoauth2client --verbose config authorize --app manage_research_exports` and share the output with us again to see whether there is more information that we can use to help you.
4) try to remove the pickle file (you can find it in the verbose output above) and retry again. 

Thanks a lot!
Zhaojun

Btw: this issue is probably best posted in [courseraoauth2client](https://github.com/coursera/courseraoauth2client) project instead of the current project.
